### ISSUE TITLE
Hey there, a note of encouragement!

### ISSUE THREAD

**Issue by shortjared** [jmalonzo/hn-now#1]
I wanted to leave a note of encouragement... I was just looking for something I could drop in my terminal based dash with a bit of filtering to get HN at a glance. Seems like two of us are thinking the same thing at the same time.

Going to keep tabs on this!

**Comment by jmalonzo** [comment]
Hey @shortjared! Thanks a lot! That's pretty much the use case lol (HN at a glance), though will add more options as need be.

Please feel free to raise an issue/enhancement if there's anything you want it to be able to do :)
